name: Terraform Multi-stage CI/CD

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  # ----- JOB 1 TERRAFORM PLAN -----
  JOB 1 - Teraform-PLAN:
    runs-on: self-hosted
  
    defaults:
      run:
        working-directory: Environments/test-env

    steps:

      - name: STEP-1 - Checkout repository
        uses: actions/checkout@v4

      - name: STEP-2 - Login to Azure using OIDC
        uses: azure/login@v3 
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: STEP-3 - Check Terraform Version
        run: terraform version

      - name: STEP-4 - Terraform Init
        run: terraform init

      - name: STEP-5 - Terraform Validate
        run: terraform validate

      - name: STEP-6 - Teraform Plan 
        run: terraform plan -out=tfplan

      - name: STEP-7 - Upload Teraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: Environments/test-env/tfplan


  # ----- JOB 2 TERRAFORM APPLY ----- 
  JOB 2 - Terraform-APPLY:
    needs: Teraform-PLAN
    runs-on: self-hosted

    defaults:
      run:
        working-directory: Environments/test-env

    steps:
      - name: STEP-1 - Checkout repo
        uses: actions/checkout@v4

      - name: STEP-2 - Login to Azure
        uses: azure/login@v3
        with: 
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: STEP-3 - Terraform Init
        run: terraform init

      - name: STEP-4 - Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: Environments/test-env

      - name: STEP-5 - Terraform Apply
        run: terraform apply --auto-approve tfplan
